import { describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { KOKORO_PROTOCOL_IDENTITY } from "./protocol.js";
import { hashKokoroAssetFile, kokoroIdentitySidecarPath, kokoroRuntimeIdentitySidecarPath, resolveKokoroAssetIdentity, resolveKokoroRuntimeIdentity, verifyKokoroAssets } from "./identity-sidecar.js";

async function fixture() { const root = await mkdtemp(join(tmpdir(), "kokoro-id-")); const modelPath = join(root, "model.onnx"); const voicesPath = join(root, "voices.bin"); await writeFile(modelPath, "model-a"); await writeFile(voicesPath, "voices-a"); return { root, cacheDir: join(root, "cache"), modelPath, voicesPath, backendVersion: "v1", protocolIdentity: KOKORO_PROTOCOL_IDENTITY }; }

describe("Kokoro asset identity", () => {
  test("hashes bytes, writes path-free sidecar, and changes on replacement", async () => { const options = await fixture(); const first = await resolveKokoroAssetIdentity(options); const text = await readFile(kokoroIdentitySidecarPath(options), "utf8"); expect(text).not.toContain(options.modelPath); await writeFile(options.modelPath, "model-b"); const second = await resolveKokoroAssetIdentity(options); expect(second.modelSha256).not.toBe(first.modelSha256); });
  test("uses compatible sidecar only when both assets are absent", async () => { const options = await fixture(); const fresh = await resolveKokoroAssetIdentity(options); await rm(options.modelPath); await rm(options.voicesPath); expect(await resolveKokoroAssetIdentity(options)).toEqual({ ...fresh, freshlyVerified: false }); await expect(verifyKokoroAssets(options, fresh)).rejects.toThrow(/missing/); });
  test("fails closed for partial assets, corrupt and incompatible sidecars", async () => { const options = await fixture(); await resolveKokoroAssetIdentity(options); await rm(options.modelPath); await expect(resolveKokoroAssetIdentity(options)).rejects.toThrow(/partial assets/); await rm(options.voicesPath); await writeFile(kokoroIdentitySidecarPath(options), "bad"); await expect(resolveKokoroAssetIdentity(options)).rejects.toThrow(/corrupt/); });
  test("detects TOCTOU asset changes before synthesis", async () => { const options = await fixture(); const identity = await resolveKokoroAssetIdentity(options); await writeFile(options.voicesPath, "changed"); await expect(verifyKokoroAssets(options, identity)).rejects.toThrow(/changed/); });
  test("rejects symlink assets and enforces cancellation and size bounds", async () => { const options = await fixture(); const link = join(options.root, "model-link.onnx"); await symlink(options.modelPath, link); await expect(hashKokoroAssetFile(link)).rejects.toThrow(/regular file/); const controller = new AbortController(); controller.abort(new DOMException("stop hashing", "AbortError")); await expect(hashKokoroAssetFile(options.modelPath, { signal: controller.signal })).rejects.toThrow("stop hashing"); await expect(hashKokoroAssetFile(options.modelPath, { maxAssetBytes: 2 })).rejects.toThrow(/safety limit/); });
  test("stores a path-free runtime identity and reuses it only for the same locator and version", async () => { const options = await fixture(); const runtime = { backendVersion: "v1", modelSha256: "a".repeat(64), voicesSha256: "b".repeat(64) }; const input = { cacheDir: options.cacheDir, runtimeLocator: JSON.stringify(["/private/kokoro", ["--secret-path"]]), protocolIdentity: options.protocolIdentity, expectedBackendVersion: "v1" }; expect(await resolveKokoroRuntimeIdentity({ ...input, advertised: runtime })).toEqual(runtime); const text = await readFile(kokoroRuntimeIdentitySidecarPath(input), "utf8"); expect(text).not.toContain("/private/kokoro"); expect(text).not.toContain("--secret-path"); expect(await resolveKokoroRuntimeIdentity(input)).toEqual(runtime); await expect(resolveKokoroRuntimeIdentity({ ...input, expectedBackendVersion: "v2" })).rejects.toThrow(/incompatible/); });
});
