import { describe, expect, test } from "bun:test";
import { access, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createNarrationRequest, prepareNarrationProviderRequest } from "@demohunter/tts-core";
import { kokoro, KOKORO_LANGUAGES } from "./kokoro-provider.js";

const fixtureWorker = join(import.meta.dir, "../test/fixtures/jsonl-worker.ts");
async function setup(mode = "ok") { const root = await mkdtemp(join(tmpdir(), "kokoro-provider-")); const modelPath = join(root, "model.onnx"); const voicesPath = join(root, "voices.bin"); await writeFile(modelPath, "model"); await writeFile(voicesPath, "voices"); const plugin = kokoro({ runtime: "command", executable: process.execPath, args: [fixtureWorker, mode], modelPath, voicesPath, modelVersion: "1", startupTimeoutMs: 500, requestTimeoutMs: 500, shutdownTimeoutMs: 500 }); return { root, modelPath, voicesPath, plugin }; }
function request(language = "en-US", overrides = {}) { return createNarrationRequest({ provider: "kokoro", model: "kokoro", voice: "en_us_male_1", language, format: "wav", sampleRate: 24000, instructions: "", text: "Unicode café 日本語", providerOptions: { speed: 1 }, ...overrides }); }

describe("Kokoro provider", () => {
  test("declares exact capabilities and accepts every normalized supported language", async () => { const { root, plugin } = await setup(); expect(plugin.capabilities).toEqual({ offlineSynthesis: true, languages: KOKORO_LANGUAGES, outputFormats: ["wav"], sampleRates: [24000], instructions: "unsupported" }); for (const language of KOKORO_LANGUAGES) expect((await prepareNarrationProviderRequest(plugin, request(language.toUpperCase()), { cacheDir: join(root, "cache"), signal: new AbortController().signal })).language).toBe(language); await plugin.close?.({}); });
  test.each([["", {}], ["de", {}], ["en-US", { format: "mp3" }], ["en-US", { sampleRate: 22050 }], ["en-US", { instructions: "whisper" }], ["en-US", { providerOptions: { speed: 0 } }]])("rejects invalid language/options %#", async (language, overrides) => { const { root, plugin } = await setup(); await expect(prepareNarrationProviderRequest(plugin, request(language as string, overrides), { cacheDir: join(root, "cache"), signal: new AbortController().signal })).rejects.toThrow(); await plugin.close?.({}); });
  test("portable identity redacts all runtime and asset paths", async () => { const { root, modelPath, voicesPath, plugin } = await setup(); const prepared = await prepareNarrationProviderRequest(plugin, request(), { cacheDir: join(root, "cache"), signal: new AbortController().signal }); const text = JSON.stringify(prepared.providerOptions); for (const forbidden of [process.execPath, fixtureWorker, modelPath, voicesPath, root]) expect(text).not.toContain(forbidden); expect(text).toMatch(/[a-f0-9]{64}/); await plugin.close?.({}); });
  test("synthesizes a sealed WAV and finalize removes staging idempotently", async () => { const { root, plugin } = await setup(); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const prepared = await prepareNarrationProviderRequest(plugin, request(), context); const result = await plugin.synthesize(prepared, context); expect(result.output.kind).toBe("file"); if (result.output.kind === "file") { await access(result.output.path); await result.output.finalize?.({ status: "persisted" }); await result.output.finalize?.({ status: "persisted" }); await expect(access(result.output.path)).rejects.toThrow(); } await plugin.close?.({}); });
  test("missing assets can prepare from sidecar but cannot synthesize a cache miss", async () => { const { root, modelPath, voicesPath, plugin } = await setup(); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; await prepareNarrationProviderRequest(plugin, request(), context); await rm(modelPath); await rm(voicesPath); const stale = await prepareNarrationProviderRequest(plugin, request(), context); await expect(plugin.synthesize(stale, context)).rejects.toThrow(/missing/); await plugin.close?.({}); });
  test.each(["wrong-format", "wrong-rate"])("rejects worker lying with %s and cleans staging", async mode => { const { root, plugin } = await setup(mode); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const prepared = await prepareNarrationProviderRequest(plugin, request(), context); await expect(plugin.synthesize(prepared, context)).rejects.toThrow(); await plugin.close?.({}).catch(() => undefined); });
});
