import { describe, expect, test } from "bun:test";
import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createNarrationRequest, prepareNarrationProviderRequest } from "@demohunter/tts-core";
import { kokoro, KOKORO_LANGUAGES } from "./kokoro-provider.js";

const fixtureWorker = join(import.meta.dir, "../test/fixtures/jsonl-worker.ts");
async function setup(mode = "ok") { const root = await mkdtemp(join(tmpdir(), "kokoro-provider-")); const modelPath = join(root, "model.onnx"); const voicesPath = join(root, "voices.bin"); await writeFile(modelPath, "model"); await writeFile(voicesPath, "voices"); const plugin = kokoro({ runtime: "command", executable: process.execPath, args: [fixtureWorker, mode], modelPath, voicesPath, modelVersion: "fixture-1", startupTimeoutMs: 500, requestTimeoutMs: 500, shutdownTimeoutMs: 500 }); return { root, modelPath, voicesPath, plugin }; }
function request(language = "en-US", overrides = {}) { return createNarrationRequest({ provider: "kokoro", model: "kokoro", voice: "en_us_male_1", language, format: "wav", sampleRate: 24000, instructions: "", text: "Unicode café 日本語", providerOptions: { speed: 1 }, ...overrides }); }

describe("Kokoro provider", () => {
  test("declares exact capabilities and accepts every normalized supported language", async () => { const { root, plugin } = await setup(); expect(plugin.capabilities).toEqual({ offlineSynthesis: true, languages: KOKORO_LANGUAGES, outputFormats: ["wav"], sampleRates: [24000], instructions: "unsupported" }); for (const language of KOKORO_LANGUAGES) expect((await prepareNarrationProviderRequest(plugin, request(language.toUpperCase()), { cacheDir: join(root, "cache"), signal: new AbortController().signal })).language).toBe(language); await plugin.close?.({}); });
  test.each([["", {}], ["de", {}], ["en-US", { format: "mp3" }], ["en-US", { sampleRate: 22050 }], ["en-US", { instructions: "whisper" }], ["en-US", { providerOptions: { speed: 0 } }]])("rejects invalid language/options %#", async (language, overrides) => { const { root, plugin } = await setup(); await expect(prepareNarrationProviderRequest(plugin, request(language as string, overrides), { cacheDir: join(root, "cache"), signal: new AbortController().signal })).rejects.toThrow(); await plugin.close?.({}); });
  test("portable identity redacts all runtime and asset paths", async () => { const { root, modelPath, voicesPath, plugin } = await setup(); const prepared = await prepareNarrationProviderRequest(plugin, request(), { cacheDir: join(root, "cache"), signal: new AbortController().signal }); const text = JSON.stringify(prepared.providerOptions); for (const forbidden of [process.execPath, fixtureWorker, modelPath, voicesPath, root]) expect(text).not.toContain(forbidden); expect(text).toMatch(/[a-f0-9]{64}/); await plugin.close?.({}); });
  test("synthesizes a sealed WAV and finalize removes staging idempotently", async () => { const { root, plugin } = await setup(); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const prepared = await prepareNarrationProviderRequest(plugin, request(), context); const result = await plugin.synthesize(prepared, context); expect(result.output.kind).toBe("file"); if (result.output.kind === "file") { await access(result.output.path); await result.output.finalize?.({ status: "persisted" }); await result.output.finalize?.({ status: "persisted" }); await expect(access(result.output.path)).rejects.toThrow(); } await plugin.close?.({}); });
  test("missing assets can prepare from sidecar but cannot synthesize a cache miss", async () => { const { root, modelPath, voicesPath, plugin } = await setup(); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; await prepareNarrationProviderRequest(plugin, request(), context); await rm(modelPath); await rm(voicesPath); const stale = await prepareNarrationProviderRequest(plugin, request(), context); await expect(plugin.synthesize(stale, context)).rejects.toThrow(/missing/); await plugin.close?.({}); });
  test("uses verified sidecars for a cache lookup when the executable exists but missing assets prevent startup", async () => { const root = await mkdtemp(join(tmpdir(), "kokoro-offline-assets-")); const modelPath = join(root, "model.onnx"); const voicesPath = join(root, "voices.bin"); await writeFile(modelPath, "model"); await writeFile(voicesPath, "voices"); const options = { runtime: "command" as const, executable: process.execPath, args: [fixtureWorker, "assets", modelPath, voicesPath], modelPath, voicesPath, modelVersion: "fixture-1", startupTimeoutMs: 500, requestTimeoutMs: 500, shutdownTimeoutMs: 500 }; const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const online = kokoro(options); const fresh = await prepareNarrationProviderRequest(online, request(), context); await online.close?.({}); await rm(modelPath); await rm(voicesPath); const offline = kokoro(options); const stale = await prepareNarrationProviderRequest(offline, request(), context); expect(stale.providerOptions).toEqual(fresh.providerOptions); await offline.close?.({}).catch(() => undefined); });
  test("fails closed on a malformed handshake even when a verified sidecar exists", async () => { const root = await mkdtemp(join(tmpdir(), "kokoro-malformed-sidecar-")); const modelPath = join(root, "model.onnx"); const voicesPath = join(root, "voices.bin"); const workerPath = join(root, "worker.ts"); await writeFile(modelPath, "model"); await writeFile(voicesPath, "voices"); await writeFile(workerPath, await readFile(fixtureWorker, "utf8")); const options = { runtime: "command" as const, executable: process.execPath, args: [workerPath], modelPath, voicesPath, modelVersion: "fixture-1", startupTimeoutMs: 500, requestTimeoutMs: 500, shutdownTimeoutMs: 500 }; const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const valid = kokoro(options); await prepareNarrationProviderRequest(valid, request(), context); await valid.close?.({}); await writeFile(workerPath, 'process.stdout.write("not-json\\n");'); const malformed = kokoro(options); await expect(prepareNarrationProviderRequest(malformed, request(), context)).rejects.toThrow(/malformed JSON during startup/); await malformed.close?.({}).catch(() => undefined); });
  test.each(["wrong-format", "wrong-rate"])("rejects worker lying with %s and cleans staging", async mode => { const { root, plugin } = await setup(mode); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const prepared = await prepareNarrationProviderRequest(plugin, request(), context); await expect(plugin.synthesize(prepared, context)).rejects.toThrow(); await plugin.close?.({}).catch(() => undefined); });
  test("accepts a self-identifying command without host asset paths", async () => { const root = await mkdtemp(join(tmpdir(), "kokoro-command-identity-")); const plugin = kokoro({ runtime: "command", executable: process.execPath, args: [fixtureWorker, "ok"], modelVersion: "fixture-1" }); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const prepared = await prepareNarrationProviderRequest(plugin, request(), context); expect(JSON.stringify(prepared.providerOptions)).not.toContain(process.execPath); const result = await plugin.synthesize(prepared, context); if (result.output.kind === "file") await result.output.finalize?.({ status: "persisted" }); await plugin.close?.({}); });
  test("restarts a session when assets are replaced in place", async () => { const root = await mkdtemp(join(tmpdir(), "kokoro-rebind-")); const modelPath = join(root, "model.onnx"); const voicesPath = join(root, "voices.bin"); await writeFile(modelPath, "model-a"); await writeFile(voicesPath, "voices-a"); const plugin = kokoro({ runtime: "command", executable: process.execPath, args: [fixtureWorker, "assets", modelPath, voicesPath], modelPath, voicesPath, modelVersion: "fixture-1" }); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const first = await prepareNarrationProviderRequest(plugin, request(), context); const firstResult = await plugin.synthesize(first, context); if (firstResult.output.kind === "file") await firstResult.output.finalize?.({ status: "persisted" }); await writeFile(modelPath, "model-b"); const second = await prepareNarrationProviderRequest(plugin, request(), context); expect(second.providerOptions).not.toEqual(first.providerOptions); const secondResult = await plugin.synthesize(second, context); if (secondResult.output.kind === "file") await secondResult.output.finalize?.({ status: "persisted" }); await plugin.close?.({}); });
  test("reverifies assets after synthesis before returning output", async () => { const root = await mkdtemp(join(tmpdir(), "kokoro-toctou-")); const modelPath = join(root, "model.onnx"); const voicesPath = join(root, "voices.bin"); await writeFile(modelPath, "model-a"); await writeFile(voicesPath, "voices-a"); const plugin = kokoro({ runtime: "command", executable: process.execPath, args: [fixtureWorker, "mutate-assets", modelPath, voicesPath], modelPath, voicesPath, modelVersion: "fixture-1" }); const context = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const prepared = await prepareNarrationProviderRequest(plugin, request(), context); await expect(plugin.synthesize(prepared, context)).rejects.toThrow(/changed/); await plugin.close?.({}).catch(() => undefined); });
  test("rejects an outer synthesis-queue waiter immediately on cancellation", async () => { const root = await mkdtemp(join(tmpdir(), "kokoro-outer-queue-")); const plugin = kokoro({ runtime: "command", executable: process.execPath, args: [fixtureWorker, "request-timeout"], modelVersion: "fixture-1", requestTimeoutMs: 5_000, shutdownTimeoutMs: 500 }); const prepareContext = { cacheDir: join(root, "cache"), signal: new AbortController().signal }; const prepared = await prepareNarrationProviderRequest(plugin, request(), prepareContext); const activeController = new AbortController(); const queuedController = new AbortController(); const active = plugin.synthesize(prepared, { ...prepareContext, signal: activeController.signal }); const queued = plugin.synthesize(prepared, { ...prepareContext, signal: queuedController.signal }); queuedController.abort(new DOMException("queued stop", "AbortError")); const outcome = await Promise.race([queued.then(() => "resolved", (error: unknown) => error), Bun.sleep(150).then(() => "timed out")]); expect(outcome).not.toBe("timed out"); expect(outcome).toBeInstanceOf(DOMException); activeController.abort(new DOMException("active stop", "AbortError")); await active.catch(() => undefined); await plugin.close?.({}).catch(() => undefined); });
});
