import type { DemoHunterTour } from "@demohunter/sdk";
import type { Page } from "playwright";

import type { ReviewViewModel } from "../viewer/view-model.js";
import { listReviewSections, orderedChapters } from "../viewer/view-model.js";

export type CompiledReviewTour = {
  tour: DemoHunterTour;
  /** Narration lines in spoken order. Used by tests and by cache pre-warming. */
  narrationScript: string[];
};

const SCROLL_SETTLE_MS = 520;
const READ_PAUSE_MS = 320;

/**
 * Compiles a review view model into an in-memory DemoHunter tour.
 *
 * No tour file is written to disk and no separate recording engine exists: the
 * returned object is handed straight to `generateTour()`, so the review video
 * is produced by exactly the same Playwright, narration, caption, chapter, and
 * FFmpeg pipeline as every other DemoHunter demo.
 *
 * Every narration string is either authored in the review definition or a
 * deterministic template over facts already derived from Git. Nothing is
 * generated by a model at runtime.
 */
export function compileReviewTour(model: ReviewViewModel): CompiledReviewTour {
  const segments = buildNarrationSegments(model);

  return {
    narrationScript: segments.flatMap((segment) => segment.narration),
    tour: {
      id: model.review.id,
      title: model.review.title,
      async beforeRecord({ goto, page }) {
        await goto("/");
        await page.waitForSelector("html[data-review-ready='true']", { timeout: 30_000 });
        await page.waitForSelector("#overview", { state: "attached", timeout: 30_000 });
      },
      async run({ chapter, narrate, narrateWhile, page, step, highlight }) {
        for (const segment of segments) {
          await chapter(segment.chapterTitle);

          await step(segment.chapterTitle, async () => {
            const [first, ...rest] = segment.narration;

            await narrateWhile(first!, async ({ sleep }) => {
              await scrollToSection(page, segment.sectionId);
              await sleep(SCROLL_SETTLE_MS);
            });

            if (segment.highlightSelector !== undefined) {
              const target = page.locator(segment.highlightSelector).first();

              if ((await target.count()) > 0) {
                await highlight(target, { paddingPx: 10, durationMs: 900 });
              }
            }

            for (const line of rest) {
              await narrate(line);
              await page.waitForTimeout(READ_PAUSE_MS);
            }
          });
        }
      },
    },
  };
}

type NarrationSegment = {
  sectionId: string;
  chapterTitle: string;
  narration: string[];
  highlightSelector?: string;
};

export function buildNarrationSegments(model: ReviewViewModel): NarrationSegment[] {
  const sections = listReviewSections(model).filter((section) => section.kind !== "walkthrough");
  const chapters = new Map(orderedChapters(model).map((chapter) => [chapter.id, chapter]));
  const segments: NarrationSegment[] = [];

  for (const section of sections) {
    switch (section.kind) {
      case "overview": {
        segments.push({
          sectionId: section.id,
          chapterTitle: "Problem and scope",
          narration: [
            model.review.narration?.opening ?? describeOpening(model),
            model.review.problem.narration ?? model.review.problem.summary,
            ...(model.review.problem.detail === undefined ? [] : [model.review.problem.detail]),
            ...describeScope(model),
          ].filter(isNonEmpty),
          highlightSelector: "#overview .card",
        });
        break;
      }
      case "architecture": {
        const diagrams = model.review.architecture ?? [];
        segments.push({
          sectionId: section.id,
          chapterTitle: "Architecture",
          narration: [
            `The target architecture is shown in ${countPhrase(diagrams.length, "diagram")}.`,
            ...diagrams.map(
              (diagram) => diagram.narration ?? diagram.caption ?? `${diagram.title}.`,
            ),
          ].filter(isNonEmpty),
          highlightSelector: "#architecture .diagram-wrap",
        });
        break;
      }
      case "review-order": {
        const entries = model.review.reviewOrder ?? [];
        segments.push({
          sectionId: section.id,
          chapterTitle: "Recommended review order",
          narration: [
            `Read this change in ${countPhrase(entries.length, "step")}.`,
            ...entries.map((entry, index) => {
              const chapter = chapters.get(entry.chapterId);
              return `${ordinal(index + 1)}, ${chapter?.title ?? entry.chapterId}. ${entry.why}`;
            }),
          ].filter(isNonEmpty),
          highlightSelector: "#review-order .card",
        });
        break;
      }
      case "chapter": {
        const chapter = chapters.get(section.id.replace(/^chapter-/, ""));

        if (chapter === undefined) {
          break;
        }

        const evidence = model.evidenceByChapter[chapter.id] ?? [];
        segments.push({
          sectionId: section.id,
          chapterTitle: chapter.title,
          narration: [
            chapter.narration,
            describeChapterFiles(chapter.files.length, evidence.length),
            ...chapter.reviewerChecks.slice(0, 3).map((check) => `Check that ${lowerFirst(check.check)}`),
          ].filter(isNonEmpty),
          highlightSelector: `#${section.id} .evidence`,
        });
        break;
      }
      case "verification": {
        segments.push({
          sectionId: section.id,
          chapterTitle: "Verification",
          narration: describeVerification(model),
          highlightSelector: "#verification .card",
        });
        break;
      }
      case "risks": {
        const risks = model.review.risks ?? [];
        segments.push({
          sectionId: section.id,
          chapterTitle: "Risks",
          narration: [
            `There ${risks.length === 1 ? "is" : "are"} ${countPhrase(risks.length, "risk")} worth calling out.`,
            ...risks.map((risk) => `${risk.title}. ${risk.detail}${risk.mitigation === undefined ? "" : ` ${risk.mitigation}`}`),
          ],
          highlightSelector: "#risks .card",
        });
        break;
      }
      case "compatibility": {
        const notes = model.review.compatibility ?? [];
        segments.push({
          sectionId: section.id,
          chapterTitle: "Compatibility",
          narration: [
            `Compatibility impact covers ${countPhrase(notes.length, "area")}.`,
            ...notes.map((note) => `${note.area}: ${note.impact}. ${note.detail}`),
          ],
          highlightSelector: "#compatibility .card",
        });
        break;
      }
      case "security": {
        const notes = model.review.security ?? [];
        segments.push({
          sectionId: section.id,
          chapterTitle: "Security",
          narration: [
            `${countPhrase(notes.length, "security boundary")} ${notes.length === 1 ? "is" : "are"} touched by this change.`,
            ...notes.map((note) => `${note.title}. ${note.detail}`),
          ],
          highlightSelector: "#security .card",
        });
        break;
      }
      case "questions": {
        const questions = model.review.reviewerQuestions ?? [];
        segments.push({
          sectionId: section.id,
          chapterTitle: "Reviewer questions",
          narration: [
            `${countPhrase(questions.length, "open question")} for the reviewer.`,
            ...questions.map((question) => question.question),
          ],
          highlightSelector: "#questions .card",
        });
        break;
      }
      case "coverage": {
        segments.push({
          sectionId: section.id,
          chapterTitle: "Changed-file coverage",
          narration: [
            describeCoverage(model),
            ...(model.review.narration?.closing === undefined ? [] : [model.review.narration.closing]),
          ].filter(isNonEmpty),
          highlightSelector: "#coverage .coverage-summary",
        });
        break;
      }
      default:
        break;
    }
  }

  return segments.filter((segment) => segment.narration.length > 0);
}

function describeOpening(model: ReviewViewModel): string {
  const pullRequest = model.review.pullRequest?.number;

  return (
    `${model.review.title}.`
    + (pullRequest === undefined ? "" : ` This is pull request ${pullRequest}.`)
    + ` It changes ${countPhrase(model.coverage.totalCount, "file")} between the merge base `
    + `${spellSha(model.git.mergeBaseSha)} and head ${spellSha(model.git.headSha)}.`
  );
}

function describeScope(model: ReviewViewModel): string[] {
  const lines: string[] = [];
  const inScope = model.review.problem.inScope ?? [];
  const outOfScope = model.review.problem.outOfScope ?? [];
  const goals = model.review.goals ?? [];
  const nonGoals = model.review.nonGoals ?? [];

  if (inScope.length > 0) {
    lines.push(`In scope: ${joinClauses(inScope)}.`);
  }
  if (outOfScope.length > 0) {
    lines.push(`Out of scope: ${joinClauses(outOfScope)}.`);
  }
  if (goals.length > 0) {
    lines.push(`The goals are: ${joinClauses(goals)}.`);
  }
  if (nonGoals.length > 0) {
    lines.push(`Explicit non-goals: ${joinClauses(nonGoals)}.`);
  }

  return lines;
}

function describeChapterFiles(fileCount: number, evidenceCount: number): string {
  if (evidenceCount === 0) {
    return `This change set covers ${countPhrase(fileCount, "file")}.`;
  }

  return (
    `This change set covers ${countPhrase(fileCount, "file")}, with `
    + `${countPhrase(evidenceCount, "focused diff")} on screen.`
  );
}

function describeVerification(model: ReviewViewModel): string[] {
  const results = model.verification.results;

  if (!model.verification.ran) {
    return [
      `${countPhrase(results.length, "verification command")} ${results.length === 1 ? "is" : "are"} declared, `
        + "but none were executed for this artifact, so treat the results as unverified.",
    ];
  }

  const passed = results.filter((result) => result.status === "passed").length;
  const failed = results.filter((result) => result.status === "failed");

  return [
    `${countPhrase(results.length, "verification command")} ran for this artifact. `
      + `${passed} passed${failed.length === 0 ? "" : ` and ${failed.length} failed`}.`,
    ...results.map(
      (result) =>
        `${result.label}: ${result.status}, exit code `
        + `${result.exitCode === null ? "unavailable" : result.exitCode}, in ${formatSeconds(result.durationMs)}.`,
    ),
  ];
}

function describeCoverage(model: ReviewViewModel): string {
  const { accountedCount, totalCount, complete } = model.coverage;
  const groups = model.coverage.groups.filter((group) => group.paths.length > 0);
  const groupClause = groups.length === 0
    ? ""
    : ` ${countPhrase(groups.length, "coverage group")} accounts for supporting files such as `
      + `${joinClauses(groups.slice(0, 3).map((group) => group.title))}.`;

  if (!complete) {
    return (
      `Coverage is incomplete: only ${accountedCount} of ${totalCount} changed files are accounted for.`
      + groupClause
    );
  }

  return (
    `All ${totalCount} changed files are accounted for: `
    + `${model.coverage.assignments.filter((assignment) => assignment.kind === "chapter").length} explained directly by a change set, `
    + `${model.coverage.assignments.filter((assignment) => assignment.kind === "group").length} grouped.`
    + groupClause
  );
}

async function scrollToSection(page: Page, sectionId: string): Promise<void> {
  await page.evaluate((id) => {
    const target = document.getElementById(id);

    if (target !== null) {
      window.scrollTo({
        top: Math.max(0, target.getBoundingClientRect().top + window.scrollY - 24),
        behavior: "smooth",
      });
    }
  }, sectionId);
}

function countPhrase(count: number, noun: string): string {
  return `${count} ${noun}${count === 1 ? "" : "s"}`;
}

function ordinal(value: number): string {
  const names = ["first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth", "tenth"];

  return names[value - 1] ?? `step ${value}`;
}

function joinClauses(items: readonly string[]): string {
  const cleaned = items.map((item) => item.replace(/\.$/, ""));

  if (cleaned.length <= 1) {
    return cleaned[0] ?? "";
  }

  return `${cleaned.slice(0, -1).join(", ")}, and ${cleaned[cleaned.length - 1]}`;
}

/** Reads a sha as spaced characters so speech synthesis does not slur it. */
function spellSha(sha: string): string {
  return sha.slice(0, 7).split("").join(" ");
}

function formatSeconds(durationMs: number): string {
  const seconds = Math.max(1, Math.round(durationMs / 1000));

  return `${seconds} second${seconds === 1 ? "" : "s"}`;
}

function lowerFirst(text: string): string {
  return text.length === 0 ? text : text[0]!.toLowerCase() + text.slice(1);
}

function isNonEmpty(value: string | undefined): value is string {
  return typeof value === "string" && value.trim().length > 0;
}
